# 基本设置
title: Hiky 加密观察
SEOTitle: Hiky4714 加密观察 | 欧易（OKX）资讯与币价追踪
description: "hiky4714.github.io 的加密货币博客：聚焦欧易（OKX）教程与API/交易机器人、比特币/以太坊/TON/ADA/DOGE等币价与USDT汇率换算（人民币、MYR、AED、EUR、SOL、LTC），并跟踪Pi Network、PEPE等热门话题与行情解读。"
keyword: "欧易, 欧 易 官网, окх, OKX, OKX交易所, okx trading bot, okx api, okx pi coin price, pi network okx, okz, usdt兑人民币, 人民币兑USDT, usdt to myr, aed to usdt, eur to usdt, usd to solana, usd to ltc, btc usdt, doge usdt, ton usdt, pepe usdt, ada cardano price, egld, btc行情, btc价格美元, 比特 幣 價格, 狗狗币价格, picoin value, why is bitcoin down today, 特朗普币走势, corleo kawasaki price, wonnimami"
url: "https://hiky4714.github.io"
baseurl: ""
github_username:    hiky4714
header-img: img/post-bg-desk.jpg

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# 插件
plugins:
  - jekyll-paginate

# 排除文件
exclude:
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - less
